# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='pixel_clock_info.proto',
  package='',
  serialized_pb='\n\x16pixel_clock_info.proto\"Q\n\x14PixelClockInfoBuffer\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x12\x12\n\ntime_stamp\x18\x02 \x01(\x03\x12\x11\n\tdirection\x18\x03 \x02(\x05')




_PIXELCLOCKINFOBUFFER = descriptor.Descriptor(
  name='PixelClockInfoBuffer',
  full_name='PixelClockInfoBuffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channel_id', full_name='PixelClockInfoBuffer.channel_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time_stamp', full_name='PixelClockInfoBuffer.time_stamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='direction', full_name='PixelClockInfoBuffer.direction', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=107,
)



class PixelClockInfoBuffer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PIXELCLOCKINFOBUFFER
  
  # @@protoc_insertion_point(class_scope:PixelClockInfoBuffer)

# @@protoc_insertion_point(module_scope)
